### ISSUE TITLE
App crashes on clicking the Toggle Mode radio Button

### ISSUE THREAD

**Issue by PrajwalM2212** [JBossOutreach/lead-management-android#117]
![screenshot_1537962888](https://user-images.githubusercontent.com/30733262/46078235-2fcaeb80-c1b1-11e8-9f7a-67c45e1d3812.png)

The logs 
`Process: com.community.jboss.leadmanagement, PID: 4559
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.community.jboss.leadmanagement/com.community.jboss.leadmanagement.main.MainActivity}: java.lang.IllegalStateException: FirebaseApp name [DEFAULT] already exists!
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                   Caused by: java.lang.IllegalStateException: FirebaseApp name [DEFAULT] already exists!
                                                                                      at com.google.android.gms.common.internal.zzbq.zza(Unknown Source:8)
                                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:91)
                                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:3)
                                                                                      at com.community.jboss.leadmanagement.main.MainActivity.onCreate(MainActivity.java:104)
                                                                                      at android.app.Activity.performCreate(Activity.java:6975)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                      at android.os.Looper.loop(Looper.java:164) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

**Comment by aakashbansal** [comment]
I would like to work on this issue.

**Comment by aakashbansal** [comment]
I have solved the issue. It was a Firebase reintialization error. Someone please review it.
https://github.com/JBossOutreach/lead-management-android/pull/119

**Comment by KeenWarrior** [comment]
closed with #119
