### ISSUE TITLE
Fix version number for Database Schema, which causes the app to crash.

### ISSUE THREAD

**Issue by krnblni** [JBossOutreach/lead-management-android#276]
Here is the error message from Logcat.

Reproduce by: Just run the app.

```
2018-11-08 23:27:29.212 26048-26125/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.community.jboss.leadmanagement, PID: 26048
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:119)
        at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:100)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:133)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:310)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
        at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
        at com.community.jboss.leadmanagement.data.daos.ContactDao_Impl$4.compute(ContactDao_Impl.java:245)
        at com.community.jboss.leadmanagement.data.daos.ContactDao_Impl$4.compute(ContactDao_Impl.java:231)
        at android.arch.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-11-08 23:27:47.213 26143-26231/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.community.jboss.leadmanagement, PID: 26143
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:119)
        at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:100)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:133)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:310)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
        at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
        at com.community.jboss.leadmanagement.data.daos.ContactDao_Impl$4.compute(ContactDao_Impl.java:245)
        at com.community.jboss.leadmanagement.data.daos.ContactDao_Impl$4.compute(ContactDao_Impl.java:231)
        at android.arch.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-11-08 23:27:47.215 26143-26231/? E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
```

**Comment by Khukhuna** [comment]
This app is not in production so we don't need to write migrations.
Simply uninstall app & reinstall it again. It should fix the error
